#!/usr/bin/env python3
#coding: utf-8

from sys import argv

from usage import help
from checkArgs import ArgumentManager
from game import Game


def main():

    argsManager = ArgumentManager()

    if argsManager.needHelp(argv):
        help()
    elif argsManager.checkArgs(argv) == 84:
        exit(84)
    else:
        return Game().run()


if __name__ == "__main__":
    main()
