#!/usr/bin/env python3
#coding: utf-8

######################################################
#                                                    #
#                Workshop Python3 (2/4)              #
#                      ---------                     #
#                Corentin COUTRET-ROZET              #
#                                                    #
# Github: https://github.com/sheiiva/Workshop_Python #
######################################################


from sys import argv

from usage import usage
from checkArgs import needHelp, checkArgs
from game import run


def main():

    if needHelp(argv):
        usage()
    elif checkArgs(argv) == 84:
        exit(84)
    else:
        run(int(argv[1]))


if __name__ == "__main__":
    main()
